platform :ios, '15.0'

target 'App' do
  use_frameworks! :linkage => :static
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
end
